name: CD workflow

on:
  push:
    branches:
      - main
      - workflow
    pull_request:

jobs:
  gather-files:
    name: Gather files for compression
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build .zip file
              # only include all .json, images, .css, .html, .js files
        run:  zip -r lorem_chrome . -i "*.json" "*.png" "*.css" "*.html" "*.js"
      
      - name: Upload .zip (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: lorem-chrome-zip   # variable name for future workflow
          path: ./lorem_chrome.zip   # path to .zip