name: CD workflow

on:
  push:
    branches:
      - main
      - workflow

jobs:
  gather-files:
    name: Gather files for compression
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build .zip file
              # only include all .json, images, .css, .html, .js files
        run:  zip -r lorem_chrome . -i "*.json" "*.png" "*.css" "*.html" "*.js"
      
      - name: Upload .zip (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: lorem-chrome-zip   # variable name for future workflow
          path: ./lorem_chrome.zip   # path to .zip

  upload-extension:
    name: Upload updated extension
    runs-on: ubuntu-latest
    # needs: gather-files
    env:
      CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      CODE: 4/1AfJohXna7V2JZJY0mK3xGlwpqgH2NiTIc1SA7GZIJR5LB7U9V3ol8K9j_uw
    steps:
      - name: install dependencies
        run: sudo apt-get -y install curl jq

      - name: request access token
        run: |-
          curl "https://accounts.google.com/o/oauth2/token" -d \
            "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&code=$CODE&grant_type=authorization_code&redirect_uri=urn:ietf:wg:oauth:2.0:oob"
          
