name: Github PR Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      

jobs:
  Check-Version-Number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get list of files changed
        id: get-files-list
        run: |-
          files_string=$(git diff --name-only -r HEAD^1 HEAD | xargs)
          echo "changed_files=$files_string" >> $GITHUB_OUTPUT

        
      - name: Display result
        run: |
          for file in ${{ steps.get-files-list.outputs.changed_files }}; do
              echo "$file was changed"
          done

      - name: Check if pulll-request-check.yml is changed
        uses: actions/github-script@v7
        with:
          script: |
            let stringArr = (`${{steps.get-files-list.outputs.changed_files}}`).split(" ");
            if (!stringArr.includes('manifest.json')){
              throw new Error ("manifest.json is not updated. Check if version number is updated.");
            }
